### ISSUE TITLE
!yt @(((aFatFinley))) crash

### ISSUE THREAD

**Issue by aaronshappell** [aaronshappell/picabot#21]
Typing `!yt @(((aFatFinley)))` crashed pica.

**Comment by aaronshappell** [comment]
```
2017-07-17T21:09:12.891574+00:00 app[worker.1]: /app/picabot.js:239
2017-07-17T21:09:12.891589+00:00 app[worker.1]:                             addSong(message, "https://www.youtube.com/watch?v=" + data.items[0].id.videoId);
2017-07-17T21:09:12.891590+00:00 app[worker.1]:                                                                                                ^
2017-07-17T21:09:12.891590+00:00 app[worker.1]:
2017-07-17T21:09:12.891591+00:00 app[worker.1]: TypeError: Cannot read property 'id' of undefined
2017-07-17T21:09:12.891594+00:00 app[worker.1]:     at Request._callback (/app/node_modules/google-auth-library/lib/transporters.js:106:7)
2017-07-17T21:09:12.891592+00:00 app[worker.1]:     at /app/picabot.js:239:96
2017-07-17T21:09:12.891596+00:00 app[worker.1]:     at emitTwo (events.js:106:13)
2017-07-17T21:09:12.891595+00:00 app[worker.1]:     at Request.self.callback (/app/node_modules/request/request.js:188:22)
2017-07-17T21:09:12.891597+00:00 app[worker.1]:     at Request.emit (events.js:191:7)
2017-07-17T21:09:12.891597+00:00 app[worker.1]:     at Request.<anonymous> (/app/node_modules/request/request.js:1171:10)
2017-07-17T21:09:12.891598+00:00 app[worker.1]:     at emitOne (events.js:96:13)
2017-07-17T21:09:12.891598+00:00 app[worker.1]:     at Request.emit (events.js:188:7)
2017-07-17T21:09:12.891599+00:00 app[worker.1]:     at IncomingMessage.<anonymous> (/app/node_modules/request/request.js:1091:12)
2017-07-17T21:09:12.891600+00:00 app[worker.1]:     at IncomingMessage.g (events.js:292:16)
2017-07-17T21:09:13.054985+00:00 heroku[worker.1]: State changed from up to crashed
```

**Comment by aaronshappell** [comment]
Happens with @Crumster or mentioning other people aka when there are no search results. Credit: @dylan-thinnes
