### ISSUE TITLE
Error and crash after !clear

### ISSUE THREAD

**Issue by aaronshappell** [aaronshappell/picabot#42]
```
TypeError: Cannot read property 'url' of undefined
2017-08-20T18:23:23.805175+00:00 app[worker.1]:     at playSong (/app/picabot.js:478:31)
2017-08-20T18:23:23.805176+00:00 app[worker.1]:     at /app/picabot.js:463:5
2017-08-20T18:23:23.805177+00:00 app[worker.1]:     at process._tickCallback (internal/process/next_tick.js:109:7)
```
Does not say now playing "song" after this occurs and trying to use !yt

**Comment by aaronshappell** [comment]
Sometimes doesn't have the error but the same behavior. Doesn't matter when !clear is called.
